[package]
name = "pleepbot_api"
version = "0.1.0"
description = "An api for pleepbot"
edition.workspace = true
publish.workspace = true

[dependencies]
actix-web.workspace = true
dotenvy.workspace = true
envy.workspace = true
serde.workspace = true
