[advisories]
ignore = [
    # Paste is unmaintained
    "RUSTSEC-2024-0436",
]

[licenses]
allow = [
    "MIT",
    "Apache-2.0",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "Unicode-3.0",
    "ISC",
    "Zlib",
    "CC0-1.0",
    "MPL-2.0",
]
confidence-threshold = 0.9

[bans]
multiple-versions = "allow"
