[package]
name = "pleepbot"
version = "0.1.0"
description = "A Twitch bot"
edition.workspace = true
publish.workspace = true

[dependencies]
dotenvy.workspace = true
envy.workspace = true
seventv.workspace = true
twitch-irc.workspace = true
twitch_api.workspace = true
twitch_bot.workspace = true
