[package]
name = "db"
version = "0.1.0"
description = ""
edition.workspace = true
publish.workspace = true

[dependencies]
dotenvy.workspace = true
envy.workspace = true
serde.workspace = true
sqlx.workspace = true
